name=input("professer Nedd")
print("we want to know if you like programming!")
print()
print("Do you like programming "+name+"")
answer=input()
print("Great! You said "+answer+"")
print("let's learn some python today")
input("press to exit")
